[package]
name = "caustics-build"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
walkdir = "2"
proc-macro2 = "1.0"
uuid = "1.0"
chrono = "0.4"
serde_json = "1.0"
heck = "0.5.0"
